// Static data extracted from ../template.html (Oct 2024 calendar)
// In a real app these would come from the Laravel backend via Inertia props.

export const monthMeta = {
  label: 'Oktober 2026',
  displayed: 'Oktober 2026',
};

export const metrics = [
  {
    key: 'total',
    label: 'Total Karyawan',
    value: '148',
    sub: 'Karyawan Aktif',
    icon: 'badge',
    badge: '100% Terdaftar',
    badgeColor: 'text-tertiary',
    footer: 'Shift 1 & 2',
    color: 'bg-surface-container-high',
  },
  {
    key: 'ontime',
    label: 'Tepat Waktu',
    value: '132',
    sub: '89.2%',
    icon: 'verified',
    badge: '89.2%',
    badgeColor: 'bg-tertiary-fixed text-on-tertiary-fixed-variant',
    footer: null,
    color: 'bg-tertiary-fixed',
    iconColor: 'text-on-tertiary-fixed-variant',
    valueColor: 'text-tertiary',
    track: { width: '89.2%', color: 'bg-tertiary-container' },
  },
  {
    key: 'late',
    label: 'Terlambat',
    value: '7',
    sub: '4.7%',
    icon: null,
    badge: '4.7%',
    badgeColor: 'bg-secondary-fixed text-on-secondary-fixed-variant',
    footer: null,
    color: 'bg-secondary-fixed',
    iconColor: 'text-on-secondary-fixed-variant',
    valueColor: 'text-secondary',
    track: { width: '4.7%', color: 'bg-secondary' },
  },
  {
    key: 'leave',
    label: 'Cuti & Izin',
    value: '18',
    sub: '12.2%',
    icon: 'leave',
    badge: '12.2%',
    badgeColor: 'bg-primary-fixed text-on-primary-fixed',
    footer: null,
    color: 'bg-primary-fixed',
    iconColor: 'text-on-primary-fixed',
    valueColor: 'text-primary',
    track: { width: '12.2%', color: 'bg-primary-container' },
  },
  {
    key: 'absent',
    label: 'Absent / Alpha',
    value: '6',
    sub: '4.0%',
    icon: null,
    badge: '4.0%',
    badgeColor: 'bg-error-container text-on-error-container',
    footer: null,
    color: 'bg-error-container',
    iconColor: 'text-on-error-container',
    valueColor: 'text-error',
    track: { width: '4.0%', color: 'bg-error' },
  },
];

// Selected date detail header
export const selectedDate = {
  day: 'Kamis, 24 Oktober 2026',
  recordCount: '148 catatan absensi terverifikasi',
};

// Calendar day cells for October 2024
// status: 'present' | 'late' | 'leave' | 'absent' | 'weekend' | 'spillover' | 'selected'
// counts: { hadir, late, cuti, alpha }
export const calendarDays = [
  // spillover from Sep
  { day: 30, month: 'Sep', status: 'spillover' },
  // Oct 1-6 (week 1)
  { day: 1, status: 'present', counts: { hadir: 140, late: 5 } },
  { day: 2, status: 'present', counts: { hadir: 142, cuti: 4 } },
  { day: 3, status: 'present', counts: { hadir: 138, late: 8 } },
  { day: 4, status: 'present', counts: { hadir: 139, alpha: 2 } },
  { day: 5, status: 'weekend' },
  { day: 6, status: 'weekend' },
  // Oct 7-13 (week 2)
  { day: 7, status: 'present', counts: { hadir: 144 } },
  { day: 8, status: 'present', counts: { hadir: 141 } },
  { day: 9, status: 'late', counts: { hadir: 135, late: 9 } },
  { day: 10, status: 'present', counts: { hadir: 137, cuti: 7 } },
  { day: 11, status: 'present', counts: { hadir: 137 } },
  { day: 12, status: 'weekend' },
  { day: 13, status: 'weekend' },
  // Oct 14-20 (week 3)
  { day: 14, status: 'present', counts: { hadir: 143 } },
  { day: 15, status: 'present', counts: { hadir: 139 } },
  { day: 16, status: 'late', counts: { hadir: 138, late: 6 } },
  { day: 17, status: 'present', counts: { hadir: 145 } },
  { day: 18, status: 'absent', counts: { hadir: 140, alpha: 1 } },
  { day: 19, status: 'weekend' },
  { day: 20, status: 'weekend' },
  // Oct 21-27 (week 4) — 24 Oct is the selected day
  { day: 21, status: 'present', counts: { hadir: 138 } },
  { day: 22, status: 'late', counts: { hadir: 135, late: 5 } },
  { day: 23, status: 'present', counts: { hadir: 137, cuti: 4 } },
  { day: 24, status: 'selected', counts: { hadir: 132, late: 7, cuti: 6, alpha: 3 } },
  { day: 25, status: 'present', counts: { hadir: 135 } },
  { day: 26, status: 'weekend' },
  { day: 27, status: 'weekend' },
  // Oct 28-31 (week 5)
  { day: 28, status: 'present', counts: { hadir: 140 } },
  { day: 29, status: 'present', counts: { hadir: 141 } },
  { day: 30, status: 'late', counts: { hadir: 138, late: 6 } },
  { day: 31, status: 'present', counts: { hadir: 138 } },
  // spillover to Nov
  { day: 1, month: 'Nov', status: 'spillover' },
  { day: 2, month: 'Nov', status: 'spillover' },
  { day: 3, month: 'Nov', status: 'spillover' },
];

export const dayHeaders = ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'];

// Employee records shown in the right panel (filtered by selected date)
export const employees = [
  {
    name: 'Budi Santoso',
    empId: 'EMP-0042',
    role: 'X.1 • NISN',
    status: 'absent',
    statusLabel: 'Masuk',
    statusPill: 'bg-error text-on-error',
    icon: 'warning',
    iconColor: 'text-error',
    note: 'Masuk Pada Pelajaran',
    shift: 'Shift 08:30 - 17:30',
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDc8oCl3Bp9LL4ZLva1hmCey8SsghLzEjAliPpoazyVu8DssrvOUDfMsiLNChJGorGzMh48OhuI9wSAQarhouASmUrkYXBpU78_HDFYRSVBIr6bb4I_BiGlBfnFMz_YH7XZaoPwc2xz9LQKDf8JN9XIogxzLGJwvhhHK62xShrV8e4sJFzPdH67KFQkV3uAKv4ECy4uR3Px32umjmNlM3o89OcYe-6OqCyt-hUbV8h7F0qVBNDU0yrmVw',
    alt: 'Close up professional portrait of an Indonesian male software engineer with glasses looking slightly concerned against a clean office background',
  },
  {
    name: 'Siti Rahmawati',
    empId: 'EMP-0105',
    role: 'UI/UX Designer • Product Team',
    status: 'leave',
    statusLabel: 'Cuti Tahunan',
    statusPill: 'bg-primary text-on-primary',
    icon: 'verified_user',
    iconColor: 'text-primary',
    note: 'Disetujui HRD (Surat cuti terlampir)',
    duration: 'Durasi: 3 Hari (23-25 Okt)',
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDSQiZLdx3UOnz_B1j_C0gZr8UYGkbJKb9aTRoR9Y8w5JHMPKpP3LoDGzAcLCBLBSqLZhO38A6gQrjiQrcovcHpXNf2g7ca9MTDJLnTPn-j1x8wVDOFfvuceJyEyGiMCGgJFpCArfcSZDUO2-jsdYuzTyngjsDrgbL9rsb2-y3sRCypqxzVicnuPLPPc4lEiZMnqZgCwNXmgivpdotQK7qhg2zF9o2uKGA5EPYr0Fq84WwmT-2yw2z9JQ',
    alt: 'Portrait of an Indonesian woman UI/UX designer wearing modern corporate casual hijab smiling warmly in bright co-working studio',
    actions: [{ label: 'Unduh Dokumen Cuti', icon: 'attachment', pill: 'bg-surface-container hover:bg-surface-container-high text-primary' }],
  },
  {
    name: 'Dimas Anggara',
    empId: 'EMP-0089',
    role: 'Business Development • Growth',
    status: 'leave',
    statusLabel: 'Izin Sakit',
    statusPill: 'bg-primary text-on-primary',
    icon: 'clinical_notes',
    iconColor: 'text-primary',
    note: 'Surat dokter terlampir • RS Medika',
    valid: 'Valid 1 Hari',
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB_LZlIYh26o4NkgS0_L9zS-Bks4acfOf4YsXBh0JoWJA-KYhFw6-fNs8jqdmfiDF3FsO1bY4oPXWwy-GKJI2lmBRqUwbPQ4j8WzUfplOjNZkhykTwoUhObjCIOwqtaQ6A2mN16cINVRL7PCTVAAVLXQQkkkEd4i0veB20nK76JuQbAmI1bM-qptasnkTfI8SY4dV_xH11XBMr5dpXAyK8hGj8ALHEKTMqMV1pMgXrK0tocjTUlBpM4aQ',
    alt: 'Corporate headshot of an Asian man business development specialist in a tailored dark blue shirt against a minimalist office background',
    actions: [{ label: 'Lihat Surat Medis', icon: 'visibility', pill: 'bg-surface-container hover:bg-surface-container-high text-on-surface' }],
  },
  {
    name: 'Reza Pratama',
    empId: 'EMP-0123',
    role: 'QA Analyst • Tech Hub',
    status: 'late',
    statusLabel: 'Terlambat 65 Menit',
    statusPill: 'bg-secondary text-on-secondary',
    icon: null,
    iconColor: null,
    note: 'Alasan: Kendala Lalu Lintas (Pohon tumbang tol barat)',
    time: 'Jam Masuk: 09:35 WIB',
    tolerance: 'Toleransi: 08:30 WIB',
    gps: 'GPS Presisi: 4 meter',
    actions: [{ label: 'Sesuaikan Jam Kerja', icon: 'schedule', pill: 'bg-surface-container hover:bg-surface-container-high text-secondary font-semibold' }],
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDlm2afiAo0NZ5gcP3h3gbTg5qAKOGW63HEeN-cl-B4ZfQAagponWSN-hPSrZe-XgNYHf-C_iMeTAkqTkwGB1oxj1j1E5kkvsnCNvNkkCmvfuMG1hS1eCHUwYuvaK7-EMkxR4DMMUHkogvaz3RWR8COjH_Ui2LN0RK-HwgnSemG6FlW4DvnGDq1zxSvHcVdoZaXQ-5rLRuNdoHWDiAVhds8GhC6F1nLqMU7kpNMRCRE5LATfbHwe7BcSw',
    alt: 'Headshot of a focused Southeast Asian QA analyst sitting at a tech workstation with soft monitor lighting on face',
  },
  {
    name: 'Maya Indah',
    empId: 'EMP-0078',
    role: 'Account Executive • Commercial',
    status: 'late',
    statusLabel: 'Terlambat 42 Menit',
    statusPill: 'bg-secondary text-on-secondary',
    icon: null,
    iconColor: null,
    note: 'Clock-in QR Kantor',
    time: 'Jam Masuk: 09:12 WIB',
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB25eOWcP7_OPCyOoPaXcExXY4yCjwjJ_le7EbWCSi414L6_FrDCo6bSzh5hAvG7bBWo6T8pxPCT-Hw-FIGr0qOayshs5rMywtGwxAWv19XdUrL0hXH9690HBaJ1WQweTrSBN4HLt-g8WsakCDYinoPW-SKazb0xAQd7_IJIsryMCnvHkos95YfG-zeVZm0ERDcwvpu52AZz-FMak5NZ2ZhOIMjhzCls20xVlEOvYq-u4MT_3DaVfm56Q',
    alt: 'Portrait of an elegant young Asian professional woman in corporate attire with neat blazer in office boardroom',
  },
  {
    name: 'Nadia Putri',
    empId: 'EMP-0019',
    role: 'Finance Specialist • Accounting',
    status: 'present',
    statusLabel: 'Hadir Tepat Waktu',
    statusPill: 'bg-tertiary text-on-tertiary',
    icon: 'fingerprint',
    iconColor: 'text-tertiary',
    note: 'Kantor Pusat HQ Lt. 4',
    time: 'Masuk: 08:15 WIB',
    verification: 'Selfie Verifkasi Valid',
    actions: [{ label: 'Lihat Foto Biometrik', icon: 'image', pill: 'text-primary hover:underline font-semibold' }],
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAdI4FIy-7JzD7Ev6W8n-E45BFZ_iLPL6NeU8O33NURhvagemik6qGK2Mfs0n8SCwdpOpNo8qpLG3r1mKhiCjCaUhTFWuc-7BElqUR0-D-syYO_btsh_dvVz-BDOydBGARrZnnIf-2pzTKFX1pWeh53JtolBdi-WcqOINO-KZmK03HmgjTwgril9vFYIrghPavWbrwQZABAH_0tW0wiXL1MwY9ql8uPgv42Lh0FiwXPJbNHVoIh2OZARg',
    alt: 'Professional corporate headshot of a confident Indonesian female finance specialist in smart beige attire against an executive office background',
  },
  {
    name: 'Fajar Nugraha',
    empId: 'EMP-0056',
    role: 'DevOps Engineer • Infrastructure',
    status: 'present',
    statusLabel: 'WFH Valid',
    statusPill: 'bg-secondary text-on-secondary',
    icon: 'wifi_tethering',
    iconColor: 'text-secondary',
    note: 'IP VPN Terverifikasi',
    time: 'Masuk: 08:28 WIB',
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBj23GnwelJaW5nzxhT38eoP-uUjFlQRonh0XmB9QpZrbkdaJ6ALuHqDssnwmLNxclMK4Zc_w3pmfnrs3wFd5zWre2l7MKHq6U2c6UXpm1kUDM3uHNPWiQkdK80NAsDUNjNLAgAK9EJPhidvakD5WVxwRQigZ77A5NrhdXfc1yOtIVpUz-iDdUY407Y8A6i_fibbK-e81Bhcv7f_9ItYpLuREADJuYFqPVsUWHxfI6LQAi4rHP9iv8WDw',
    alt: 'Portrait of an energetic Indonesian DevOps engineer working from a minimalist home studio desk with ergonomic monitors',
  },
];
